apiVersion: v1 # for versions before 1.9.0 use apps/v1beta2
kind: Namespace
metadata:
  name: hello
  labels:
   name: hello
---
apiVersion: v1 # for versions before 1.9.0 use apps/v1beta2
kind: Service
metadata:
  name: hello-app-service
  namespace: hello
  labels:
    name: hello
spec:
  type: NodePort
  selector:
    app: hello-app
  ports: 
    - protocol: TCP
      nodePort: 30000 #external service port (node level)
      port: 8081 #internal cluster port
      targetPort: 8080 #to the pod port/containers 
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: hello-app-deployment
  namespace: hello
spec:
  selector:
    matchLabels:
      app: hello-app
  replicas: 2 # tells deployment to run 2 pods matching the template
  template: #to pods
    metadata:
      namespace: hello
      labels:
        app: hello-app #app N
    spec:
      containers:
      - name: nginx-hello
        image: estebansantiago/nginx-hello:latest
        ports:
        - containerPort: 8080
      - name: node-hello
        image: estebansantiago/node-hello:latest
        ports:
        - containerPort: 3000